#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -eo pipefail

CHANGED_FILES=$(git diff --name-only --cached --diff-filter=ACMR)

get_pattern_files() {
    pattern=$(echo "$*" | sed "s/ /\$\\\|/g")
    echo "$CHANGED_FILES" | { grep "$pattern$" || true; }
}

ELM_FILES=$(get_pattern_files .elm)

if [[ -n "$ELM_FILES" ]]
then
    yarn elm-review
fi
